<?php

namespace GurmeInvoice\Enum;

class Currency extends BaseEnum
{
    public const AFN = 'AFN';
    public const DZD = 'DZD';
    public const ARS = 'ARS';
    public const AWG = 'AWG';
    public const AUD = 'AUD';
    public const AZM = 'AZM';
    public const BSD = 'BSD';
    public const BHD = 'BHD';
    public const THB = 'THB';
    public const PAB = 'PAB';
    public const BBD = 'BBD';
    public const BYR = 'BYR';
    public const BZD = 'BZD';
    public const BMD = 'BMD';
    public const VEB = 'VEB';
    public const BOB = 'BOB';
    public const BGN = 'BGN';
    public const BRL = 'BRL';
    public const BND = 'BND';
    public const BIF = 'BIF';
    public const CAD = 'CAD';
    public const CVE = 'CVE';
    public const KYD = 'KYD';
    public const GHC = 'GHC';
    public const XAF = 'XAF';
    public const XPF = 'XPF';
    public const CLP = 'CLP';
    public const COP = 'COP';
    public const KMF = 'KMF';
    public const NIO = 'NIO';
    public const CRC = 'CRC';
    public const CUP = 'CUP';
    public const CYP = 'CYP';
    public const CZK = 'CZK';
    public const DKK = 'DKK';
    public const GMD = 'GMD';
    public const MKD = 'MKD';
    public const AED = 'AED';
    public const DJF = 'DJF';
    public const STD = 'STD';
    public const DOP = 'DOP';
    public const VND = 'VND';
    public const AMD = 'AMD';
    public const XCD = 'XCD';
    public const EGP = 'EGP';
    public const SVC = 'SVC';
    public const ETB = 'ETB';
    public const EUR = 'EUR';
    public const FKP = 'FKP';
    public const FJD = 'FJD';
    public const HUF = 'HUF';
    public const CDF = 'CDF';
    public const GIP = 'GIP';
    public const XAU = 'XAU';
    public const HTG = 'HTG';
    public const PYG = 'PYG';
    public const GNF = 'GNF';
    public const GYD = 'GYD';
    public const HKD = 'HKD';
    public const UAH = 'UAH';
    public const ISK = 'ISK';
    public const INR = 'INR';
    public const IQD = 'IQD';
    public const IRR = 'IRR';
    public const JMD = 'JMD';
    public const JOD = 'JOD';
    public const KES = 'KES';
    public const PGK = 'PGK';
    public const LAK = 'LAK';
    public const EEK = 'EEK';
    public const HRK = 'HRK';
    public const KWD = 'KWD';
    public const MWK = 'MWK';
    public const AOA = 'AOA';
    public const MMK = 'MMK';
    public const GEL = 'GEL';
    public const LVL = 'LVL';
    public const LBP = 'LBP';
    public const ALL = 'ALL';
    public const HNL = 'HNL';
    public const SLL = 'SLL';
    public const ROL = 'ROL';
    public const LRD = 'LRD';
    public const LYD = 'LYD';
    public const SZL = 'SZL';
    public const LTL = 'LTL';
    public const LSL = 'LSL';
    public const MGF = 'MGF';
    public const MYR = 'MYR';
    public const MTL = 'MTL';
    public const TMM = 'TMM';
    public const MUR = 'MUR';
    public const MZM = 'MZM';
    public const MXN = 'MXN';
    public const MDL = 'MDL';
    public const MAD = 'MAD';
    public const NGN = 'NGN';
    public const ERN = 'ERN';
    public const NAD = 'NAD';
    public const NPR = 'NPR';
    public const ANG = 'ANG';
    public const YUM = 'YUM';
    public const ILS = 'ILS';
    public const TWD = 'TWD';
    public const NZD = 'NZD';
    public const KPW = 'KPW';
    public const NOK = 'NOK';
    public const BTN = 'BTN';
    public const PEN = 'PEN';
    public const MRO = 'MRO';
    public const TOP = 'TOP';
    public const PKR = 'PKR';
    public const XPD = 'XPD';
    public const MOP = 'MOP';
    public const UYU = 'UYU';
    public const PHP = 'PHP';
    public const XPT = 'XPT';
    public const GBP = 'GBP';
    public const BWP = 'BWP';
    public const QAR = 'QAR';
    public const GTQ = 'GTQ';
    public const ZAR = 'ZAR';
    public const OMR = 'OMR';
    public const KHR = 'KHR';
    public const MVR = 'MVR';
    public const RON = 'RON';
    public const IDR = 'IDR';
    public const RUB = 'RUB';
    public const RWF = 'RWF';
    public const SAR = 'SAR';
    public const XDR = 'XDR';
    public const SCR = 'SCR';
    public const XAG = 'XAG';
    public const SGD = 'SGD';
    public const SKK = 'SKK';
    public const SBD = 'SBD';
    public const SOS = 'SOS';
    public const LKR = 'LKR';
    public const KGS = 'KGS';
    public const TJS = 'TJS';
    public const SHP = 'SHP';
    public const SDD = 'SDD';
    public const SRG = 'SRG';
    public const SEK = 'SEK';
    public const CHF = 'CHF';
    public const SYP = 'SYP';
    public const BDT = 'BDT';
    public const WST = 'WST';
    public const TZS = 'TZS';
    public const KZT = 'KZT';
    public const SIT = 'SIT';
    public const TTD = 'TTD';
    public const MNT = 'MNT';
    public const TND = 'TND';
    public const TRY = 'TRY';
    public const UGX = 'UGX';
    public const USD = 'USD';
    public const UZS = 'UZS';
    public const VUV = 'VUV';
    public const KRW = 'KRW';
    public const YER = 'YER';
    public const JPY = 'JPY';
    public const CNY = 'CNY';
    public const ZWD = 'ZWD';
    public const PLN = 'PLN';

    public static function alias(string $value): string
    {
        $aliases = [
            self::AFN => 'Afghani',
            self::DZD => 'Algerian Dinar',
            self::ARS => 'Argentine Peso',
            self::AWG => 'Aruban Guilder',
            self::AUD => 'Australian Dollar',
            self::AZM => 'Azerbaijanian Manat',
            self::BSD => 'Bahamian Dollar',
            self::BHD => 'Bahraini Dinar',
            self::THB => 'Baht',
            self::PAB => 'Balboa',
            self::BBD => 'Barbados Dollar',
            self::BYR => 'Belarussian Ruble',
            self::BZD => 'Belize Dollar',
            self::BMD => 'Bermudian Dollar',
            self::VEB => 'Bolivar',
            self::BOB => 'Boliviano',
            self::BGN => 'Bulgarian Lev',
            self::BRL => 'Brazilian Real',
            self::BND => 'Brunei Dollar',
            self::BIF => 'Burundi Franc',
            self::CAD => 'Canadian Dollar',
            self::CVE => 'Cape Verde Escudo',
            self::KYD => 'Cayman Islands Dollar',
            self::GHC => 'Cedi',
            self::XAF => 'CFA Franc',
            self::XPF => 'CFP Franc',
            self::CLP => 'Chilean Peso',
            self::COP => 'Colombian Peso',
            self::KMF => 'Comoro Franc',
            self::NIO => 'Cordoba Oro',
            self::CRC => 'Costa Rican Colon',
            self::CUP => 'Cuban Peso',
            self::CYP => 'Cyprus Pound',
            self::CZK => 'Czech Koruna',
            self::DKK => 'Danish Krone',
            self::GMD => 'Dalasi',
            self::MKD => 'Denar',
            self::AED => 'Dirham',
            self::DJF => 'Djibouti Franc',
            self::STD => 'Dobra',
            self::DOP => 'Dominican Peso',
            self::VND => 'Dong',
            self::AMD => 'Dram',
            self::XCD => 'East Carribean Dollar',
            self::EGP => 'Egyptian Pound',
            self::SVC => 'El Salvador Colon',
            self::ETB => 'Ethopian Birr',
            self::EUR => 'Euro',
            self::FKP => 'Falkland Islands Pound',
            self::FJD => 'Fiji Dollar',
            self::HUF => 'Forint',
            self::CDF => 'Franc Congolais',
            self::GIP => 'Gibraltar Pound',
            self::XAU => 'Gold',
            self::HTG => 'Gourde',
            self::PYG => 'Guarani',
            self::GNF => 'Guinea Franc',
            self::GYD => 'Guyana Dollar',
            self::HKD => 'HKD',
            self::UAH => 'Hryvnia',
            self::ISK => 'Iceland Krona',
            self::INR => 'Indian Rupee',
            self::IQD => 'Iraqi Dinar',
            self::IRR => 'Iranian Rial',
            self::JMD => 'Jamaican Dollar',
            self::JOD => 'Jordanian Dinar',
            self::KES => 'Kenyan Shilling',
            self::PGK => 'Kina',
            self::LAK => 'Kip',
            self::EEK => 'Kroon',
            self::HRK => 'Kuna',
            self::KWD => 'Kuwaiti Dinar',
            self::MWK => 'Kwacha',
            self::AOA => 'Kwanza',
            self::MMK => 'Kyat',
            self::GEL => 'Lari',
            self::LVL => 'Latvian Lats',
            self::LBP => 'Lebanese Pound',
            self::ALL => 'Lek',
            self::HNL => 'Lempira',
            self::SLL => 'Leone',
            self::ROL => 'Leu',
            self::LRD => 'Liberian Dollar',
            self::LYD => 'Libyan Dinar',
            self::SZL => 'Lilangeni',
            self::LTL => 'Lithuanian Litas',
            self::LSL => 'Loti',
            self::MGF => 'Malagasy Franc',
            self::MYR => 'Malaysian Ringgit',
            self::MTL => 'Maltese Lira',
            self::TMM => 'Manat',
            self::MUR => 'Mauritius Rupee',
            self::MZM => 'Metical',
            self::MXN => 'Mexican Peso',
            self::MDL => 'Moldovan Leu',
            self::MAD => 'Morrocan Dirham',
            self::NGN => 'Naira',
            self::ERN => 'Nakfa',
            self::NAD => 'Namibia Dollar',
            self::NPR => 'Nepalese Rupee',
            self::ANG => 'Netherlands Antillian Guilder',
            self::YUM => 'New Dinar',
            self::ILS => 'New Israeli Sheqel',
            self::TWD => 'New Taiwan Dollar',
            self::NZD => 'New Zealand Dollar',
            self::KPW => 'North Korean Won',
            self::NOK => 'Norwegian Krone',
            self::BTN => 'Ngultrum',
            self::PEN => 'Nuevo Sol',
            self::MRO => 'Ouguiya',
            self::TOP => 'Pa&apos;anga',
            self::PKR => 'Pakistan Rupee',
            self::XPD => 'Palladium',
            self::MOP => 'Pataca',
            self::UYU => 'Peso Uruguayo',
            self::PHP => 'Philippine Peso',
            self::XPT => 'Platinum',
            self::GBP => 'Pound Sterling',
            self::BWP => 'Pula',
            self::QAR => 'Qatari Rial',
            self::GTQ => 'Quetzal',
            self::ZAR => 'Rand',
            self::OMR => 'Rial Omani',
            self::KHR => 'Riel',
            self::MVR => 'Rufiyaa',
            self::RON => 'Rumen Leyi',
            self::IDR => 'Rupiah',
            self::RUB => 'Russian Ruble',
            self::RWF => 'Rwanda Franc',
            self::SAR => 'Saudi Riyal',
            self::XDR => 'SDR',
            self::SCR => 'Seychelles Rupee',
            self::XAG => 'Silver',
            self::SGD => 'Singapore Dollar',
            self::SKK => 'Slovak Koruna',
            self::SBD => 'Solomon Islands Dollar',
            self::SOS => 'Somali Shilling',
            self::LKR => 'Sri Lanka Rupee',
            self::KGS => 'Som',
            self::TJS => 'Somoni',
            self::SHP => 'St. Helena Pound',
            self::SDD => 'Sudanese Dinar',
            self::SRG => 'Suriname Guilder',
            self::SEK => 'Swedish Krona',
            self::CHF => 'Swiss Franc',
            self::SYP => 'Syrian Pound',
            self::BDT => 'Taka',
            self::WST => 'Tala',
            self::TZS => 'Tanzanian Shilling',
            self::KZT => 'Tenge',
            self::SIT => 'Tolar',
            self::TTD => 'Trinidad and Tobago Dollar',
            self::MNT => 'Tugrik',
            self::TND => 'Tunisian Dinar',
            self::TRY => 'Turkish Lira',
            self::UGX => 'Uganda Shilling',
            self::USD => 'American Dollar',
            self::UZS => 'Uzbekistan Sum',
            self::VUV => 'Vatu',
            self::KRW => 'Won',
            self::YER => 'Yemeni Rial',
            self::JPY => 'Yen',
            self::CNY => 'Yuan Renminbi',
            self::ZWD => 'Zimbabwe Dollar',
            self::PLN => 'Zloty',
        ];

        return $aliases[$value] ?? $value;
    }
}