<?php

namespace GurmeInvoice\Enum;

class ExemptionReason extends BaseEnum {

	public const KDV201 = '201';
	public const KDV202 = '202';
	public const KDV204 = '204';
	public const KDV205 = '205';
	public const KDV206 = '206';
	public const KDV207 = '207';
	public const KDV208 = '208';
	public const KDV209 = '209';
	public const KDV211 = '211';
	public const KDV212 = '212';
	public const KDV213 = '213';
	public const KDV214 = '214';
	public const KDV215 = '215';
	public const KDV216 = '216';
	public const KDV217 = '217';
	public const KDV218 = '218';
	public const KDV219 = '219';
	public const KDV220 = '220';
	public const KDV221 = '221';
	public const KDV223 = '223';
	public const KDV225 = '225';
	public const KDV226 = '226';
	public const KDV227 = '227';
	public const KDV228 = '228';
	public const KDV229 = '229';
	public const KDV230 = '230';
	public const KDV231 = '231';
	public const KDV232 = '232';
	public const KDV234 = '234';
	public const KDV235 = '235';
	public const KDV236 = '236';
	public const KDV237 = '237';
	public const KDV238 = '238';
	public const KDV239 = '239';
	public const KDV240 = '240';
	public const KDV241 = '241';
	public const KDV242 = '242';
	public const KDV301 = '301';
	public const KDV302 = '302';
	public const KDV303 = '303';
	public const KDV304 = '304';
	public const KDV305 = '305';
	public const KDV306 = '306';
	public const KDV307 = '307';
	public const KDV308 = '308';
	public const KDV309 = '309';
	public const KDV310 = '310';
	public const KDV311 = '311';
	public const KDV312 = '312';
	public const KDV313 = '313';
	public const KDV314 = '314';
	public const KDV315 = '315';
	public const KDV316 = '316';
	public const KDV317 = '317';
	public const KDV318 = '318';
	public const KDV319 = '319';
	public const KDV320 = '320';
	public const KDV321 = '321';
	public const KDV322 = '322';
	public const KDV323 = '323';
	public const KDV324 = '324';
	public const KDV325 = '325';
	public const KDV326 = '326';
	public const KDV327 = '327';
	public const KDV328 = '328';
	public const KDV329 = '329';
	public const KDV330 = '330';
	public const KDV331 = '331';
	public const KDV332 = '332';
	public const KDV333 = '333';
	public const KDV334 = '334';
	public const KDV335 = '335';
	public const KDV336 = '336';
	public const KDV337 = '337';
	public const KDV338 = '338';
	public const KDV339 = '339';
	public const KDV340 = '340';
	public const KDV341 = '341';
	public const KDV342 = '342';
	public const KDV343 = '343';
	public const OTV101 = '101';
	public const OTV102 = '102';
	public const OTV103 = '103';
	public const OTV104 = '104';
	public const OTV105 = '105';
	public const OTV106 = '106';
	public const OTV107 = '107';
	public const OTV108 = '108';

	public static function alias( string $value ): string {
		$aliases = [
			self::KDV201 => '17/1 Kültür ve Eğitim Amacı Taşıyan İşlemler',
			self::KDV202 => '17/2-a Sağlık, Çevre Ve Sosyal Yardım Amaçlı İşlemler',
			self::KDV204 => '17/2-c Yabancı Diplomatik Organ Ve Hayır Kurumlarının Yapacakları Bağışlarla İlgili Mal Ve Hizmet Alışları',
			self::KDV205 => '17/2-d Taşınmaz Kültür Varlıklarına İlişkin Teslimler ve Mimarlık Hizmetleri',
			self::KDV206 => '17/2-e Mesleki Kuruluşların İşlemleri',
			self::KDV207 => '17/3 Askeri Fabrika, Tersane ve Atölyelerin İşlemleri',
			self::KDV208 => '17/4-c Birleşme, Devir, Dönüşüm ve Bölünme İşlemleri',
			self::KDV209 => '17/4-e Banka ve Sigorta Muameleleri Vergisi Kapsamına Giren İşlemler',
			self::KDV211 => '17/4-h Zirai Amaçlı Su Teslimleri İle Köy Tüzel Kişiliklerince Yapılan İçme Suyu teslimleri',
			self::KDV212 => '17/4-ı Serbest Bölgelerde Verilen Hizmetler',
			self::KDV213 => '17/4-j Boru Hattı İle Yapılan Petrol Ve Gaz Taşımacılığı',
			self::KDV214 => '17/4-k Organize Sanayi Bölgelerindeki Arsa ve İşyeri Teslimleri İle Konut Yapı',
			self::KDV215 => '17/4-1 Varlık Yönetim Şirketlerinin İşlemleri',
			self::KDV216 => '17/4-m Tasarruf Mevduatı Sigorta Fonunun İşlemleri',
			self::KDV217 => '17/4-n Basın-Yayın ve Enformasyon Genel Müdürlüğüne Verilen Haber Hizmetleri',
			self::KDV218 => 'KDV 17/4-o md. Gümrük Antrepoları, Geçici Depolama Yerleri ile Gümrüklü Sahalarda Vergisiz Satış Yapılan İşyeri, Depo ve Ardiye Gibi Bağımsız Birimlerin Kiralanması',
			self::KDV219 => '17/4-p Hazine ve Arsa Ofisi Genel Müdürlüğünün işlemleri',
			self::KDV220 => '17/4-r İki Tam Yıl Süreyle Sahip Olunan Taşınmaz ve İştirak Hisseleri ile 15/7/2023 tarihinden önce kurumların aktifinde kayıtlı Taşınmaz satışı',
			self::KDV221 => 'Geçici 15 Konut Yapı Kooperatifleri, Belediyeler ve Sosyal Güvenlik Kuruluşlarına Verilen İnşaat Taahhüt Hizmeti',
			self::KDV223 => 'Geçici 20/1 Teknoloji Geliştirme Bölgelerinde Yapılan İşlemler',
			self::KDV225 => 'Geçici 23 Milli Eğitim Bakanlığına Yapılan Bilgisayar Bağışları İle İlgili Teslimler',
			self::KDV226 => '17/2-b Özel Okulları, Üniversite ve Yüksekokullar Tarafından Verilen Bedelsiz Eğitim Ve Öğretim Hizmetleri',
			self::KDV227 => '17/2-b Kanunların Gösterdiği Gerek Üzerine Bedelsiz Olarak Yapılan Teslim ve Hizmetler',
			self::KDV228 => '17/2-b Kanunun (17/1) Maddesinde Sayılan Kurum ve Kuruluşlara Bedelsiz Olarak Yapılan Teslimler',
			self::KDV229 => '17/2-b Gıda Bankacılığı Faaliyetinde Bulunan Dernek ve Vakıflara Bağışlanan Gıda, Temizlik, Giyecek ve Yakacak Maddeleri',
			self::KDV230 => '17/4-g Külçe Altın, Külçe Gümüş Ve Kiymetli Taşlarin Teslimi',
			self::KDV231 => '17/4-g Metal Plastik, Lastik, Kauçuk, Kağit, Cam Hurda Ve Atıkların Teslimi',
			self::KDV232 => '17/4-g Döviz, Para, Damga Pulu, Değerli Kağıtlar, Hisse Senedi ve Tahvil Teslimleri',
			self::KDV234 => '17/4-ş Konut Finansmanı Amacıyla Teminat Gösterilen ve İpotek Konulan Konutların Teslimi',
			self::KDV235 => '16/1-c Transit ve Gümrük Antrepo Rejimleri İle Geçici Depolama ve Serbest Bölge Hükümlerinin Uygulandığı Malların Teslimi',
			self::KDV236 => '19/2 Usulüne Göre Yürürlüğe Girmiş Uluslararası Anlaşmalar Kapsamındaki İstisnalar (İade Hakkı Tanınmayan)',
			self::KDV237 => '17/4-t 5300 Sayılı Kanuna Göre Düzenlenen Ürün Senetlerinin İhtisas/Ticaret Borsaları Aracılığıyla İlk Teslimlerinden Sonraki Teslim',
			self::KDV238 => '17/4-u Varlıkların Varlık Kiralama Şirketlerine Devri İle Bu Varlıkların Varlık Kiralama Şirketlerince Kiralanması ve Devralınan Kuruma Devri',
			self::KDV239 => '17/4-y Taşınmazların Finansal Kiralama Şirketlerine Devri, Finansal Kiralama Şirketi Tarafından Devredene Kiralanması ve Devri',
			self::KDV240 => '17/4-z Patentli Veya Faydalı Model Belgeli Buluşa İlişkin Gayri Maddi Hakların Kiralanması, Devri ve Satışı',
			self::KDV241 => 'TürkAkım Gaz Boru Hattı Projesine İlişkin Anlaşmanın (9/b) Maddesinde Yer Alan Hizmetler',
			self::KDV242 => 'KDV 17/4-ö md. Gümrük Antrepoları, Geçici Depolama Yerleri ile Gümrüklü Sahalarda, İthalat ve İhracat İşlemlerine konu mallar ile transit rejim kapsamında işlem gören mallar için verilen ardiye, depolama ve terminal hizmetleri',
			self::KDV301 => '11/1-a Mal İhracatı (KDV)',
			self::KDV302 => '11/1-a Hizmet İhracatı (KDV)',
			self::KDV303 => '11/1-a Roaming Hizmetleri (KDV)',
			self::KDV304 => '13/a Deniz Hava ve Demiryolu Taşıma Araçlarının Teslimi İle İnşa, Tadil, Bakım ve Onarımları (KDV)',
			self::KDV305 => '13/b Deniz ve Hava Taşıma Araçları İçin Liman Ve Hava Meydanlarında Yapılan Hizmetler (KDV)',
			self::KDV306 => '13/c Petrol Aramaları ve Petrol Boru Hatlarının İnşa ve Modernizasyonuna İlişkin Yapılan Teslim ve Hizmetler (KDV)',
			self::KDV307 => '13/c Maden Arama, Altın, Gümüş ve Platin Madenleri İçin İşletme, Zenginleştirme Ve Rafinaj Faaliyetlerine İlişkin Teslim Ve Hizmetler[KDVGUT-(II/8-4)] (KDV)',
			self::KDV308 => '13/d Teşvikli Yatırım Mallarının Teslimi (KDV)',
			self::KDV309 => '13/e Liman Ve Hava Meydanlarının İnşası, Yenilenmesi Ve Genişletilmesi (KDV)',
			self::KDV310 => '13/f Ulusal Güvenlik Amaçlı Teslim ve Hizmetler (KDV)',
			self::KDV311 => '14/1 Uluslararası Taşımacılık (KDV)',
			self::KDV312 => '15/a Diplomatik Organ Ve Misyonlara Yapılan Teslim ve Hizmetler (KDV)',
			self::KDV313 => '15/b Uluslararası Kuruluşlara Yapılan Teslim ve Hizmetler (KDV)',
			self::KDV314 => '19/2 Usulüne Göre Yürürlüğe Girmiş Uluslar Arası Anlaşmalar Kapsamındaki İstisnalar (KDV)',
			self::KDV315 => '14/3 İhraç Konusu Eşyayı Taşıyan Kamyon, Çekici ve Yarı Romorklara Yapılan Motorin Teslimleri (KDV)',
			self::KDV316 => '11/1-a Serbest Bölgelerdeki Müşteriler İçin Yapılan Fason Hizmetler (KDV)',
			self::KDV317 => '17/4-s Engellilerin Eğitimleri, Meslekleri ve Günlük Yaşamlarına İlişkin Araç-Gereç ve Bilgisayar Programları (KDV)',
			self::KDV318 => 'Geçici 29 3996 Sayılı Kanuna Göre Yap-İşlet-Devret Modeli Çerçevesinde Gerçekleştirilecek Projeler, 3359 Sayılı Kanuna Göre Kiralama Karşılığı Yaptırılan Sağlık Tesislerine İlişkin Projeler ve 652 Sayılı Kanun Hükmünde Kararnameye Göre Kiralama Karşılığı Yaptırılan Eğitim Öğretim Tesislerine İlişkin Projelere İlişkin Teslim ve Hizmetler (KDV)',
			self::KDV319 => '13/g Başbakanlık Merkez Teşkilatına Yapılan Araç Teslimleri (KDV)',
			self::KDV320 => 'Geçici 16 (6111 sayılı K.) İSMEP Kapsamında İstanbul İl Özel İdaresi\'ne Bağlı Olarak Faaliyet Gösteren "İstanbul Proje Koordinasyon Birimi"ne Yapılacak Teslim ve Hizmetler (KDV)',
			self::KDV321 => 'Geçici 26 Birleşmiş Milletler (BM) ile Kuzey Atlantik Antlaşması Teşkilatı (NATO) Temsilcilikleri ve Bu Teşkilatlara Bağlı Program, Fon ve Özel İhtisas Kuruluşları ile İktisadi İşbirliği ve Kalkınma Teşkilatına (OECD) Resmi Kullanımları İçin Yapılacak Mal Teslimi ve Hizmet İfaları, Bunların Sosyal ve Ekonomik Yardım Amacıyla Bedelsiz Olarak Yapacakları Mal Teslimi ve Hizmet İfaları İle İlgili Bunlara Yapılan Mal Teslimi ve Hizmet İfaları (KDV)',
			self::KDV322 => '11/1-a Türkiye\'de İkamet Etmeyenlere Özel Fatura ile Yapılan Teslimler (Bavul Ticareti) (KDV)',
			self::KDV323 => '13/ğ 5300 Sayılı Kanuna Göre Düzenlenen Ürün Senetlerinin İhtisas/Ticaret Borsaları Aracılığıyla İlk Teslimi (KDV)',
			self::KDV324 => '13/h Türkiye Kızılay Derneğine Yapılan Teslim ve Hizmetler ile Türkiye Kızılay Derneğinin Teslim ve Hizmetleri (KDV)',
			self::KDV325 => '13/ı Yem Teslimleri (KDV)',
			self::KDV326 => '13/ı Gıda, Tarım ve Hayvancılık Bakanlığı Tarafından Tescil Edilmiş Gübrelerin Teslimi (KDV)',
			self::KDV327 => '13/ı Gıda, Tarım ve Hayvancılık Bakanlığı Tarafından Tescil Edilmiş Gübrelerin İçeriğinde Bulunan Hammaddelerin Gübre Üreticilerine Teslimi (KDV)',
			self::KDV328 => '13/i Konut veya İşyeri Teslimleri (KDV)',
			self::KDV329 => 'Eğitimde Fırsatları Artırma ve Teknolojiyi İyileştirme Hareketi (FATİH) projesi Kapsamında Milli Eğitim Bakanlığına Yapılacak Mal Teslimi ve Hizmet İfası (KDV)',
			self::KDV330 => 'KDV 13/j md. Organize Sanayi Bölgeleri ile Küçük Sanayi Sitelerinin İnşasına İlişkin Teslim ve Hizmetler (KDV)',
			self::KDV331 => 'KDV 13/m md. Ar-Ge, Yenilik ve Tasarım Faaliyetlerinde Kullanılmak Üzere Yapılan Yeni Makina ve Teçhizat Teslimlerinde İstisna (KDV)',
			self::KDV332 => 'KDV Geçici 39. Md. İmalat Sanayiinde Kullanılmak Üzere Yapılan Yeni Makina ve Teçhizat Teslimlerinde İstisna (KDV)',
			self::KDV333 => 'KDV 13/k md. Kapsamında Genel ve Özel Bütçeli Kamu İdarelerine, İl Özel İdarelerine, Belediyelere ve Köylere bağışlanan Tesislerin İnşasına İlişkin İstisna (KDV)',
			self::KDV334 => 'KDV 13/l md. Kapsamında Yabancılara Verilen Sağlık Hizmetlerinde İstisna (KDV)',
			self::KDV335 => 'KDV 13/n Basılı Kitap ve Süreli Yayınların Teslimleri (KDV)',
			self::KDV336 => 'Geçici 40 UEFA Müsabakaları Kapsamında Yapılacak Teslim ve Hizmetler (KDV)',
			self::KDV337 => 'Türk Akım Gaz Boru Hattı Projesine İlişkin Anlaşmanın (9/h) Maddesi Kapsamındaki Gaz Taşıma Hizmetleri (KDV)',
			self::KDV338 => 'İmalatçıların Mal İhracatları (KDV)',
			self::KDV339 => 'İmalat Sanayii ile Turizme Yönelik Yatırım Teşvik Belgesi Kapsamındaki İnşaat İşlerine İlişkin Teslim ve Hizmetler (KDV)',
			self::KDV340 => 'Elektrik Motorlu Taşıt Araçlarının Geliştirilmesine Yönelik Mühendislik Hizmetleri (KDV)',
			self::KDV341 => 'Afetzedelere Bağışlanacak Konutların İnşasına İlişkin İstisna (KDV)',
			self::KDV342 => 'Genel Bütçeli Kamu İdarelerine Bağışlanacak Taşınmazların İnşasına İlişkin İstisna (KDV)',
			self::KDV343 => 'Genel Bütçeli Kamu İdarelerine Bağışlanacak Konutların Yabancı Devlet Kurum ve Kuruluşlarına Teslimine İlişkin İstisna (KDV)',
			self::OTV101 => 'İhracat İstisnası (ÖTV)',
			self::OTV102 => 'Diplomatik İstisna (ÖTV)',
			self::OTV103 => 'Askeri Amaçlı İstisna (ÖTV)',
			self::OTV104 => 'Petrol Arama Faaliyetlerinde Bulunanlara Yapılan Teslimler (ÖTV)',
			self::OTV105 => 'Uluslararası Anlaşmadan Doğan İstisna (ÖTV)',
			self::OTV106 => 'Diğer İstisnalar (ÖTV)',
			self::OTV107 => '7/a Maddesi Kapsamında Yapılan Teslimler (ÖTV)',
			self::OTV108 => 'Geçici 5. Madde Kapsamında Yapılan Teslimler (ÖTV)',
		];

		return $aliases[ $value ] ?? $value;
	}
}
